export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SET_DISHES: "SET_DISHES",
    SET_CATEGORIES: "SET_CATEGORIES",
    SET_EMPLOYEES: "SET_EMPLOYEES",
    SELECTED_PRODUCT: "SELECTED_PRODUCTS",
    DELETE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    SET_LOGIN: "SET_LOGIN"
};