export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SET_DISHES: "SET_DISHES",
    SET_BRANCHES: "SET_BRANCHES",
    SET_CATEGORIES: "SET_CATEGORIES",
    SET_EMPLOYEES: "SET_EMPLOYEES",
    SELECTED_PRODUCT: "SELECTED_PRODUCTS",
    DELETE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    SET_SELECTED_BRANCH: "SET_SELECTED_BRANCH",
    SET_SELECTED_DISH: "SET_SELECTED_DISH",
    SET_SELECTED_PRODUCT: "SET_SELECTED_PRODUCT",
    SET_SELECTED_EMPLOYEE: "SET_SELECTED_EMPLOYEE",
    SET_LOGIN: "SET_LOGIN",
    SET_TOKEN: "SET_TOKEN"
};